### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ceastman-r7** [jackc/tern#89]
I am getting the following stack trace from this section of code:

	migrationRoot, _ := fs.Sub(migrationFiles, "/workspace/db/tern")

	err = migrator.LoadMigrations(migrationRoot)

trace:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x563c653e5c27]

goroutine 1 [running]:
io/fs.ReadDir({0x0, 0x0}, {0x563c65b95510, 0x1})
	io/fs/readdir.go:33 +0x87
io/fs.glob({0x0?, 0x0?}, {0x563c65b95510, 0x1}, {0xc0001ce100, 0x1}, {0x0, 0x0, 0x0})
	io/fs/glob.go:101 +0x67
io/fs.globWithLimit({0x0, 0x0}, {0xc0001ce100, 0x1}, 0x1)
	io/fs/glob.go:63 +0x2ea
io/fs.globWithLimit({0x0, 0x0}, {0xc0001ce100, 0x7}, 0x0)
	io/fs/glob.go:72 +0x288
io/fs.Glob(...)
	io/fs/glob.go:34
github.com/jackc/tern/v2/migrate.(*Migrator).LoadMigrations(0xc0005183c0, {0x0?, 0x0})
	github.com/jackc/tern/v2@v2.1.1/migrate/migrate.go:160 +0x488
main.NewMigrator({0xc000552090?, 0x563c665633c0?})

**Comment by ceastman-r7** [comment]
missing the go embed comment

i.e. 
//go:embed data/*.sql
